feat: templates, make, readme
uuazed/crunchdao pull request #6
Opened 2023-03-20 14:34 UTC by matteoettam09

2023-03-21 07:48 UTC, uuazed requested changes

2023-03-21 07:48 UTC, uuazed commented on Makefile
> +	python3.9 -m pip install --upgrade pip
Why are you hard-coding python3.9? That should be $(PYTHON)

2023-03-21 07:48 UTC, uuazed commented on crunchdao/__init__.py
Please revert that file mode change and the same for all other files. No need to make everything executable.

2023-03-21 08:58 UTC, matteoettam09 commented on Makefile
> +	python3.9 -m pip install --upgrade pip
Thanks, pushed.

2023-03-22 07:13 UTC, uuazed approved these changes

2023-03-22 07:13 UTC, merged